pre-release-commit-message = "chore: release v{{version}}"
tag-message = "v{{version}}"

pre-release-replacements = [
  {file="README.md", search="rust-socialite = \"[0-9\\.-]+\"", replace="rust-socialite = \"{{version}}\"", exactly=1},
  {file="CHANGELOG.md", search="## \\[Unreleased\\]", replace="## [Unreleased]\n\n## [{{version}}] - {{date}}", exactly=1}
]
